WebApp/speechtox/urls.py
from django.contrib import admin
from django.conf.urls import url, include
# from text2category import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^text2category/', include('text2category.urls')),
    url(r'^songcategory/', include('songcategory.urls')),
    url(r'^playlistcategorize/', include('playlistcategorize.urls')),
    url(r'^$', views.home, name="home"),
    url(r'^team/$', views.team, name="team"),
]

urlpatterns += staticfiles_urlpatterns()

WebApp/text2category/urls.py
from django.conf.urls import url
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'text2category'

urlpatterns = [
    url(r'^$', views.create, name="file_create"),
]

urlpatterns += staticfiles_urlpatterns()

WebApp/text2category/models.py
from django.db import models

# Create your models here.
class Content(models.Model):
    body = models.TextField()

    def __str__(self):
        return self.body

WebApp/text2category/forms.py
from django import forms
from . import models

class InputForm(forms.ModelForm):
    class Meta:
        model = models.Content
        fields = ['body']

WebApp/text2category/views.py
from django.shortcuts import render, redirect
from .models import Content
from django.http import HttpResponse
from . import forms
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import re, string
re_tok = re.compile(f'([{string.punctuation}“”¨«»®´·º½¾¿¡§£₤‘’])')
# from speechtox.MLModels.ml import label

# Create your views here.


def create(request):
    if request.method == 'POST':
        form = forms.InputForm(request.POST)
        if form.is_valid():
    #         ans = label(form.cleaned_data['body'])
            vec = pickle.load(open('./../MLModels/vec.pk', 'rb'))
            X_test = [form.cleaned_data['body']]
            X_test = vec.transform(X_test)

            r  = pickle.load(open('./../MLModels/r.pk', 'rb'))

            labels = ['Toxic', 'Severe_Toxic', 'Obscene', 'Threat', 'Insult', 'Identity_Hate']
            result = "The entered text is classified as: "
            for i in range(6):
                filename = './../MLModels/log' + str(i) + str('.sav')
                model = pickle.load(open(filename, 'rb'))
                pred = model.predict(X_test.multiply(r[i]))
                if(pred==1):
                    result += labels[i] + " "
            if result == "The entered text is classified as: ":
                result = "The entered text is decent."
        #     result = ans
        return render(request, 'text2category/output.html', {'op':result})  
    else:
        form = forms.InputForm
    return render(request, 'text2category/input_create.html', {'form':form})

WebApp/text2category/templates/text2category/input_create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block one %}
<!-- <form class="w3-container w3-card-4 w3-padding-16 w3-white form-horizontal" action="/text2category/#contents" method="POST" style="margin-left: 15%; margin-right: 15%; width: 70%;">{{ form.as_p }}
{% csrf_token %}
<input type="submit" class="w3-button w3-right w3-theme">
</form> -->

<div class="w3-row-padding w3-center w3-padding-64" id="contents">
        <h2><u>TEXT CATEGORIZATION</u></h2>
        <p>Enter the text to categorize:</p><br>
        <div class="w3-col m12 s12" style="text-align: center; margin: auto;">
          <form class="w3-container w3-card-4 w3-padding-16 w3-white form-horizontal" action="/text2category/#contents" method="POST" style="margin-left: 15%; margin-right: 15%; width: 70%;">
            {% csrf_token %}
            <tr><th><label for="id_body">Body:</label></th><td><textarea name="body" cols="40" rows="10" required="" id="id_body" style="
              width: 95%;"></textarea></td></tr>
                <input type="submit" class="w3-button w3-right w3-theme">
                </form>
              </div>
            </div> 
{% endblock %}

WebApp/text2category/templates/text2category/output.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block one %}
<p id="contents" style="text-align: center;">{{ op }}</p>
{% endblock %}