WebApp/songcategory/urls.py
from django.conf.urls import url
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'songcategory'

urlpatterns = [
    url(r'^$', views.categorize, name="song_categorize"),
]

urlpatterns += staticfiles_urlpatterns()

WebApp/speechtox/urls.py
from django.contrib import admin
from django.conf.urls import url, include
# from text2category import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^text2category/', include('text2category.urls')),
    url(r'^songcategory/', include('songcategory.urls')),
    url(r'^playlistcategorize/', include('playlistcategorize.urls')),
    url(r'^$', views.home, name="home"),
    url(r'^team/$', views.team, name="team"),
]

urlpatterns += staticfiles_urlpatterns()

WebApp/songcategory/models.py
from django.db import models

# Create your models here.
class Song(models.Model):
    artist = models.CharField(max_length=50)
    song_name = models.CharField(max_length=50)

    def __str__(self):
        return self.song_name

WebApp/songcategory/forms.py
from django import forms
from . import models

class SongForm(forms.ModelForm):
    class Meta:
        model = models.Song
        fields = ['song_name', 'artist']

WebApp/songcategory/views.py
from django.shortcuts import render, redirect
from .models import Song
from django.http import HttpResponse
from . import forms
import requests
from bs4 import BeautifulSoup
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import re, string
re_tok = re.compile(f'([{string.punctuation}“”¨«»®´·º½¾¿¡§£₤‘’])')

# Create your views here.
model = []
for i in range(6):
    filename = './../MLModels/log' + str(i) + str('.sav')
    model.append(pickle.load(open(filename, 'rb')))
vec = pickle.load(open('./../MLModels/vec.pk', 'rb'))
r  = pickle.load(open('./../MLModels/r.pk', 'rb'))
labels = ['Toxic', 'Severe_Toxic', 'Obscene', 'Threat', 'Insult', 'Identity_Hate']



def categorize(request):
    if request.method == 'POST':
        form = forms.SongForm(request.POST)
        if form.is_valid():
            artist = "-".join(list(form.cleaned_data['artist'].lower().split(" ")))
            name = "-".join(list(form.cleaned_data['song_name'].lower().split(" ")))
            query_url = "https://genius.com/" + artist + "-" + name + "-lyrics"
            print(query_url)
            page = requests.get(query_url)
            html = BeautifulSoup(page.text, "html.parser")
            lyricsdiv = html.find("div", class_="lyrics")
            if lyricsdiv != None:
                lyrics = lyricsdiv.get_text()
            else:
                res = "Invalid song/artist."
                return render(request, 'songcategory/output.html', {'op':res})         
            f=0
            rem = []
            for i in range(len(lyrics)):    
                if f==1:
                    if lyrics[i] == ']':
                        f=0
                    continue
                if lyrics[i]=='[':
                    f=1
                    continue
                rem.append(lyrics[i])	
            lyrics = ''.join(rem)
            X_test = [lyrics]
            #X_test = list(X_test)
            #X_test = pd.DataFrame(X_test[0], columns=['comment_text'])
            X_test = vec.transform(X_test)
            result = "The given song is classified as:<br>"
            for i in range(6):
                #filename = './../MLModels/log' + str(i) + str('.sav')
                #model = pickle.load(open(filename, 'rb'))
                pred = model[i].predict(X_test.multiply(r[i]))
                if(pred==1):
                    result += labels[i] + "<br>"
                else:
                    result += ""
            # print(result)
            # and returning a file output.csv which will have the result.
            # f1 = open("./text2category/output.csv", "r")
            # op = f1.read()
            if result == "The given song is classified as:<br>":
                result = "The given song is decent."
        return render(request, 'songcategory/output.html', {'op':result})  
        # return HttpResponse("Done")
    else:
        form = forms.SongForm
    return render(request, 'songcategory/song_details.html', {'form':form})

WebApp/songcategory/templates/songcategory/output.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block one %}
<p id="contents" style="text-align: center;">{{ op | safe }}</p>
{% endblock %}

WebApp/songcategory/templates/songcategory/song_details.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block one %}
<div class="w3-row-padding w3-center w3-padding-64" id="contents">
  <h2><u>SONG CATEGORIZATION</u></h2>
  <p>Enter the name of the song and its artist to categorize:</p><br>
  <div class="w3-col s12 m12" style="text-align: center; margin: 0 auto;">
    <form class="w3-container w3-card-4 w3-padding-16 w3-white form-horizontal" action="/songcategory/#contents" method="POST" style="margin-left: 15%; margin-right: 15%; width: 70%;">
      {% csrf_token %}
        <p><label for="id_song_name">Song name:</label> <input type="text" name="song_name" maxlength="50" required id="id_song_name" style="width:95%;"/></p>
      <p><label for="id_artist">Artist:</label> <input type="text" name="artist" maxlength="50" required id="id_artist" style="width:95%;"/></p>
    <input type="submit" class="w3-button w3-right w3-theme">
    </form>
  </div>
</div>            
{% endblock %}